#!/usr/bin/env bash

. "$XVM_ROOT/scripts/functions"

version_path=$XVM_ROOT/versions/go
env_path=$XVM_ROOT/envs/go

default_version=$(cat $version_path/default)
if command -v go >/dev/null 2>&1; then
    current_version=$(go env GOVERSION)
else
    current_version=""
fi

[[ "$1" = "" ]] &&
	display_fatal "Please specify the version"

version=$1
if [[ ! $version =~ ^go ]]; then
	version="go$version"
fi

if [[ -d $version_path/$version ]]; then
	rm -rf $version_path/$version
	rm -rf $env_path/$version
	display_message "golang $version has been uninstalled successfully"

    if [[ $version == $current_version ]]; then
        display_message "$version is the current version, please use 'xvm go use <version>' to switch to another version"
    fi

    if [[ $version == $default_version ]]; then
		rm -rf $env_path/default
		rm -rf $version_path/default
        display_message "$default_version is the default version, please use 'xvm go use <version> --default' to switch to another version"
    fi

else
	display_fatal "golang $version is not installed"
fi
