#!/usr/bin/env bash

. "$XVM_ROOT/scripts/functions"

version_path=$XVM_ROOT/versions/node
env_path=$XVM_ROOT/envs/node

default_version=$(cat $version_path/default)
current_version=$(node -v)

[[ "$1" = "" ]] &&
	display_fatal "Please specify the version"

version=$1

if [[ ! $version =~ ^v ]]; then
	version="v$version"
fi

if [[ -d $version_path/$version ]]; then
	rm -rf $version_path/$version
	rm -rf $env_path/$version
	rm -rf $env_path/default
	rm -rf $version_path/default
	display_message "Node.js $version has been uninstalled successfully"

    if [[ $version == $current_version ]]; then
        display_message "$version is the current version, please use 'xvm node use <version>' to switch to another version"
    fi

    if [[ $version == $default_version ]]; then
        display_message "Node.js $default_version is the default version, please use 'xvm node use <version> --default' to switch to another version"
    fi

else
	display_fatal "Node.js $version is not installed"
fi
