#!/usr/bin/env bash

version_path="$XVM_ROOT/versions/go"
env_path="$XVM_ROOT/envs/go"

mkdir -p "$version_path"
mkdir -p "$env_path"

. "$XVM_ROOT/scripts/functions"

show_usage() {
    echo "Usage: xvm go <command> [options]"
    echo "Commands:"
    echo "  -h, --help     Show help for xvm go"
    echo "  list           List all installed versions of go"
    echo "  ls-remote      List all remote versions of go"
    echo "  default        Set a specific version as the default"
    echo "  install        Install a specific version of go"
    echo "  uninstall      Uninstall a specific version of go"
    echo "  use            Use a specific version of go"
}

main() {
    if [ $# -eq 0 ]; then
        show_usage
        exit 1
    fi

    check_curl
    check_git

    COMMAND=$1
    shift

    case $COMMAND in
        "--help"|"-h")
            show_usage
            ;;
        "list"|"ls")
            bash "$XVM_ROOT/scripts/go-scripts/list" "$@"
            ;;
        "ls-remote")
            bash "$XVM_ROOT/scripts/go-scripts/ls-remote" "$@"
            ;;
        "default")
            bash "$XVM_ROOT/scripts/go-scripts/default" "$@"
            ;;
        "install")
            bash "$XVM_ROOT/scripts/go-scripts/install" "$@"
            ;;
        "uninstall")
            bash "$XVM_ROOT/scripts/go-scripts/uninstall" "$@"
            ;;
        *)
            display_fatal "Unrecognized command line argument: '$COMMAND'"
            ;;
    esac    
}

main "$@"
