#!/usr/bin/env bash

if [ -z "$XVM_ROOT" ]; then
    echo "XVM_ROOT not set. Please source ~/.xvm/xvm"
    exit 1
fi

. "$XVM_ROOT/scripts/functions" || exit 1

command=$1
shift

case $command in
    "--version"|"-v")
        display_message "XVM version $XVM_VERSION"
        ;;
    "--help"|"-h")
        display_message "XVM is a tool for managing multiple versions of your tools"
        ;;
    "help")
        subcommand=$1
        shift
        if [ -f "$XVM_ROOT/scripts/$command" ]; then
            bash "$XVM_ROOT/scripts/$command" "--help"
        else
            display_message "XVM is a tool for managing multiple versions of your tools"
        fi
        ;;
    *)
        if [ -f "$XVM_ROOT/scripts/$command" ]; then
            bash "$XVM_ROOT/scripts/$command" "$@"
        else
            display_fatal "Unrecognized command line argument: '$command'"
        fi
        ;;
esac

