#!/usr/bin/env bash

. "$XVM_ROOT/scripts/functions"

version_path=$XVM_ROOT/versions/python
env_path=$XVM_ROOT/envs/python

default_version=$(cat $version_path/default)
if command -v python >/dev/null 2>&1; then
    current_version=$(python --version 2>&1 | awk '{print $2}')
else
    current_version=""
fi

[[ "$1" = "" ]] &&
	display_fatal "Please specify the version"

version=$1

if [[ -d $version_path/$version ]]; then
	# 检查是否为虚拟环境
	if [ -f "$version_path/.$version" ]; then
		# 虚拟环境的卸载
		rm -rf "$version_path/$version"
		rm -f "$version_path/.$version"
		display_message "Virtual environment '$version' has been uninstalled successfully"
	else
		# 普通版本的卸载
		rm -rf "$version_path/$version"
		rm -rf "$env_path/$version"
		display_message "Python $version has been uninstalled successfully"

		if [[ $version == $current_version ]]; then
			display_message "$version is the current version, please use 'xvm python use <version>' to switch to another version"
		fi

		if [[ $version == $default_version ]]; then
			rm -rf "$env_path/default"
			rm -rf "$version_path/default"
			display_message "$default_version is the default version, please use 'xvm python use <version> --default' to switch to another version"
		fi
	fi
else
	display_fatal "Python $version is not installed"
fi
